name: Firebase Hosting
'on':
  workflow_dispatch:
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GITHUB-ACTIONS-TEST-8bd87 }}'
          channelId: live
          projectId: github-actions-test-8bd87
          entryPoint: "./frontend"